### ISSUE TITLE
HoloLens 1

### ISSUE THREAD

**Issue by Antonio-Iliev** [vbandi/HL2-ResearchMode#2]
Hi! I want to test this application on HoloLens 1. But the architecture for this device is x86. Can you provide a HL2UnityPlugin.dll for x86?

**Comment by vbandi** [comment]
Sorry - unfortunately, the plugin I'm using from https://github.com/petergu684/HoloLens2-ResearchMode-Unity is for HL2 only.

**Comment by Antonio-Iliev** [comment]
Thank you for your quick response. :)
