### ISSUE TITLE
MRTK / Visual Studio

### ISSUE THREAD

**Issue by JaVo93** [vbandi/HL2-ResearchMode#3]
hi, I tested the Project it worked fine (1-2 months ago) and I could generated the .appx, however changes through MRTK (2.5.1) or Visual Studio 2019 lead to the following errors (see picture attached). I also tried it with MRTK 2.6.1. Can someone please download the project and try the build? Maybe I missing some configuration points. My build settings are also attached. Thanks in advance.

![image](https://user-images.githubusercontent.com/59292797/111139497-7da25c80-8581-11eb-972b-aed8aa3f24bd.png)
![image](https://user-images.githubusercontent.com/59292797/111139507-8135e380-8581-11eb-8a36-4202680ce090.png)

**Comment by vbandi** [comment]
Are you using the Unity or the MRTK build window? If you're building through the Unity build window (which you have here as a screenshot), you seem to be deploying on your PC instead of the Hololens. (Build and Run on is set to Local Machine)

**Comment by JaVo93** [comment]
The MRTK build window, I cannot build in Unity-->MRTK for HL2 anymore. The way via Unity Build --> VS 2019 --> Direct to HL2 via USB cable works.

Thank you for your help.
